name: Lint

on:
  # Should only be used by other workflows
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          # use the default if on main branch, otherwise use the pull request config
          args: --timeout=30m --config=.golangci.yml
          only-new-issues: true
          skip-cache: true
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: '-exclude=G104,G115,G304,G406,G507 -exclude-dir=builtin/gen ./...'
